logging:
  level:
    org.jam.bookingservice: DEBUG

authentication:
    token-header: "Authorization"
    token: "booking-service-token"
    protected-uri-ant-pattern: "/book"
    unprotected-uri-ant-pattern: "/**"
